### ISSUE TITLE
Install fails on Windows 10, Node 12.21.0: "options.callback is not a function"

### ISSUE THREAD

**Issue by sparist** [xSlither/node-eventlog#1]
Attempting to install node-eventlog on Node 12.21.0 causes the following error:
```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: options.callback is not a function
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\...\node_modules\request\main.js:290:21)
node-pre-gyp ERR! stack     at Request.emit (events.js:314:20)
node-pre-gyp ERR! stack     at IncomingMessage.<anonymous> (C:\...\node_modules\request\main.js:278:54)
node-pre-gyp ERR! stack     at IncomingMessage.emit (events.js:326:22)
node-pre-gyp ERR! stack     at endReadableNT (_stream_readable.js:1241:12)
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\...\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--target_arch=x64" "--target_platform=win32"
node-pre-gyp ERR! cwd C:\...\node_modules\node-eventlog
node-pre-gyp ERR! node -v v12.21.0
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
```

**Comment by xSlither** [comment]
Hi sparist, thank you for taking the time to post an issue. I used [nvm for windows](https://github.com/coreybutler/nvm-windows) to install Node v12.21.0 on my Windows 10 machine. I've been using 12.18.4 successfully. 

I was able to use ```npm i node-eventlog``` successfully in a test project with Node 12.21.0.

I did a bit of research to see if there is some issue with node-pre-gyp but I could not find any information. Could you try installing with ```npm i node-eventlog --build-from-source``` ? Perhaps there is some issue retrieving the release. That flag should bypass node-pre-gyp and build from the source using node-gyp. This will require the build tools, however, to compile. 

Let me know your results, as it should help us diagnose the root cause.

**Comment by sparist** [comment]
Using `--build-from-source` seems to not exhibit the error. 👍

**Comment by xSlither** [comment]
Great! Thanks for letting me know. I'm going to leave this open until I've been able to either recreate and address or figure out the root cause.
